### ISSUE TITLE
gst-plugins-base fails to build with GCC 4.9

### ISSUE THREAD

**Issue by TimothyGu** [mxe/mxe#406]
Another intrinsics problem. Interesting part of log:

```
  CC       libgstaudioresample_la-speex_resampler_float.lo
  CC       libgstaudioresample_la-speex_resampler_double.lo
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h: In function 'interpolate_product_double':
resample_sse.h:128:11: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
   __m128d sum1 = _mm_setzero_pd();
           ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
resample_sse.h: In function 'inner_product_double':
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:103:1: error: inlining failed in call to always_inline '_mm_setzero_pd': target specific option mismatch
 _mm_setzero_pd (void)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:87:12: error: called from here
    __m128d sum = _mm_setzero_pd();
            ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:124:1: error: inlining failed in call to always_inline '_mm_loadu_pd': target specific option mismatch
 _mm_loadu_pd (double const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:90:13: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i), _mm_loadu_pd(b+i)));
             ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:124:1: error: inlining failed in call to always_inline '_mm_loadu_pd': target specific option mismatch
 _mm_loadu_pd (double const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:90:13: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i), _mm_loadu_pd(b+i)));
             ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:265:1: error: inlining failed in call to always_inline '_mm_mul_pd': target specific option mismatch
 _mm_mul_pd (__m128d __A, __m128d __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:90:13: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i), _mm_loadu_pd(b+i)));
             ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:241:1: error: inlining failed in call to always_inline '_mm_add_pd': target specific option mismatch
 _mm_add_pd (__m128d __A, __m128d __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:90:11: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i), _mm_loadu_pd(b+i)));
           ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:124:1: error: inlining failed in call to always_inline '_mm_loadu_pd': target specific option mismatch
 _mm_loadu_pd (double const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:91:13: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i+2), _mm_loadu_pd(b+i+2)));
             ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:124:1: error: inlining failed in call to always_inline '_mm_loadu_pd': target specific option mismatch
 _mm_loadu_pd (double const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:91:13: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i+2), _mm_loadu_pd(b+i+2)));
             ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:265:1: error: inlining failed in call to always_inline '_mm_mul_pd': target specific option mismatch
 _mm_mul_pd (__m128d __A, __m128d __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:91:13: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i+2), _mm_loadu_pd(b+i+2)));
             ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:241:1: error: inlining failed in call to always_inline '_mm_add_pd': target specific option mismatch
 _mm_add_pd (__m128d __A, __m128d __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:91:11: error: called from here
       sum = _mm_add_pd(sum, _mm_mul_pd(_mm_loadu_pd(a+i+2), _mm_loadu_pd(b+i+2)));
           ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:915:1: error: inlining failed in call to always_inline '_mm_unpackhi_pd': target specific option mismatch
 _mm_unpackhi_pd (__m128d __A, __m128d __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:93:10: error: called from here
    sum = _mm_add_sd(sum, _mm_unpackhi_pd(sum, sum));
          ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:247:1: error: inlining failed in call to always_inline '_mm_add_sd': target specific option mismatch
 _mm_add_sd (__m128d __A, __m128d __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:93:8: error: called from here
    sum = _mm_add_sd(sum, _mm_unpackhi_pd(sum, sum));
        ^
In file included from /root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:1266:0,
                 from resample_sse.h:38,
                 from resample.c:140,
                 from speex_resampler_double.c:26:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/emmintrin.h:173:1: error: inlining failed in call to always_inline '_mm_store_sd': target specific option mismatch
 _mm_store_sd (double *__P, __m128d __A)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_double.c:26:
resample_sse.h:94:4: error: called from here
    _mm_store_sd(&ret, sum);
    ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h: In function 'interpolate_product_single':
resample_sse.h:62:10: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
   __m128 sum = _mm_setzero_ps();
          ^
make[4]: *** [libgstaudioresample_la-speex_resampler_double.lo] Error 1
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
resample_sse.h: In function 'inner_product_single':
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:119:1: error: inlining failed in call to always_inline '_mm_setzero_ps': target specific option mismatch
 _mm_setzero_ps (void)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:46:11: error: called from here
    __m128 sum = _mm_setzero_ps();
           ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '_mm_loadu_ps': target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:49:13: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i), _mm_loadu_ps(b+i)));
             ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '_mm_loadu_ps': target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:49:13: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i), _mm_loadu_ps(b+i)));
             ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '_mm_mul_ps': target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:49:13: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i), _mm_loadu_ps(b+i)));
             ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:185:1: error: inlining failed in call to always_inline '_mm_add_ps': target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:49:11: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i), _mm_loadu_ps(b+i)));
           ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '_mm_loadu_ps': target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:50:13: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i+4), _mm_loadu_ps(b+i+4)));
             ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:933:1: error: inlining failed in call to always_inline '_mm_loadu_ps': target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:50:13: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i+4), _mm_loadu_ps(b+i+4)));
             ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:197:1: error: inlining failed in call to always_inline '_mm_mul_ps': target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:50:13: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i+4), _mm_loadu_ps(b+i+4)));
             ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:185:1: error: inlining failed in call to always_inline '_mm_add_ps': target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:50:11: error: called from here
       sum = _mm_add_ps(sum, _mm_mul_ps(_mm_loadu_ps(a+i+4), _mm_loadu_ps(b+i+4)));
           ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:786:1: error: inlining failed in call to always_inline '_mm_movehl_ps': target specific option mismatch
 _mm_movehl_ps (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:52:10: error: called from here
    sum = _mm_add_ps(sum, _mm_movehl_ps(sum, sum));
          ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:185:1: error: inlining failed in call to always_inline '_mm_add_ps': target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:52:8: error: called from here
    sum = _mm_add_ps(sum, _mm_movehl_ps(sum, sum));
        ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:745:1: error: inlining failed in call to always_inline '_mm_shuffle_ps': target specific option mismatch
 _mm_shuffle_ps (__m128 __A, __m128 __B, int const __mask)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:53:10: error: called from here
    sum = _mm_add_ss(sum, _mm_shuffle_ps(sum, sum, 0x55));
          ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:129:1: error: inlining failed in call to always_inline '_mm_add_ss': target specific option mismatch
 _mm_add_ss (__m128 __A, __m128 __B)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:53:8: error: called from here
    sum = _mm_add_ss(sum, _mm_shuffle_ps(sum, sum, 0x55));
        ^
In file included from resample_sse.h:38:0,
                 from resample.c:140,
                 from speex_resampler_float.c:27:
/root/Timothys_sandbox/mxe-test/usr/lib/gcc/i686-w64-mingw32.static/4.9.0/include/xmmintrin.h:962:1: error: inlining failed in call to always_inline '_mm_store_ss': target specific option mismatch
 _mm_store_ss (float *__P, __m128 __A)
 ^
In file included from resample.c:140:0,
                 from speex_resampler_float.c:27:
resample_sse.h:54:4: error: called from here
    _mm_store_ss(&ret, sum);
    ^
make[4]: *** [libgstaudioresample_la-speex_resampler_float.lo] Error 1
make[4]: Target `install' not remade because of errors.
make[4]: Leaving directory `/root/Timothys_sandbox/mxe-test/tmp-gst-plugins-base-i686-w64-mingw32.static/gst-plugins-base-1.2.2/gst/audioresample'
```
