### PR TITLE
ocaml-camlimages: fix for giflib >=5.1

### PR DESCRIPTION
**Pull request by tonytheodore**
See: https://github.com/mxe/mxe/pull/1423#issuecomment-233153020

Fixes the build after `giflib` update, but I can't get the current patch to apply with `make import-patch-*` or by hand with `git am`.

### CODE REVIEW

**Comment by tonytheodore** [comment]
> can't get the current patch to apply with make import-patch-*

Unrelated `gsed` issue #1444.

**Comment by starius** [comment]
Unrelated issue, breaking ocaml-camlimages:

```
File "ximage.mli", line 24, characters 9-18:
Error: Unbound module Gdk
Makefile:706: recipe for target 'ximage.cmi' failed
```

`git bisect` prints the following:

> 00ac153c906ac4b551ab51dda265fc618e140902 is the first bad commit

(00ac153c906ac4b551ab51dda265fc618e140902 was introduced by https://github.com/mxe/mxe/pull/1424)

**Comment by tonytheodore** [comment]
Can you post the log? I don't see the issue here.

**Comment by starius** [comment]
> `"fix@me" <fix@me>`

I propose to replace with `William <r.3@libertysurf.fr>`.

**Comment by starius** [comment]
> Can you post the log? I don't see the issue here.

https://github.com/mxe/mxe/commit/00ac153c906ac4b551ab51dda265fc618e140902 did not cause this problem.

I realised what the problem was caused by me running `git clean` in `mxe/usr`.

Removed files include:
```
...
Removing i686-w64-mingw32.static/lib/ocaml/lablgtk2/gdk.cmi
Removing i686-w64-mingw32.static/lib/ocaml/lablgtk2/gdk.cmx
Removing i686-w64-mingw32.static/lib/ocaml/lablgtk2/gdk.o
...
```

The log of ocaml-camlimages: https://gist.github.com/a5c960cd2912bfed9d9d600de56a7604

**Comment by starius** [comment]
`ocaml-lablgtk2` installs file `usr/i686-w64-mingw32.static/lib/ocaml/lablgtk2/.gitignore`.
I think, the problem can be fixed by ignoring all `.gitignore` files in `build-pkg`.

**Comment by starius** [comment]
Thanks!
