### ISSUE TITLE
openscenegraph is broken ('AVCod ecContext' has no member named 'get_buffer')

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1230]
Commit: 62467d9d4dbb69aa632ae684b4a5a3f4c3b4a1ff
OS: Debian Wheezy
Log: https://gist.github.com/822e7f77a7158fe79b84

Probably this problem was introduced by 57a6850a0f427fa25ec12fec2231ae640dff9f99

**Comment by TimothyGu** [comment]
This member has been deprecated for 3+ years now. It's OSG's fault they are still using it.

I'd vote for disabling the FFmpeg plugin in OSG.

**Comment by TimothyGu** [comment]
BTW, this issue has been reported back last year: http://osdir.com/ml/OpenSceneGraph-Users/2015-12/msg00021.html
