### ISSUE TITLE
Meson 0.63.0 requires python 3.7

### ISSUE THREAD

**Issue by jonaski** [mxe/mxe#2886]
@mabrand Meson 0.63.0 requires python 3.7 because of compressed in zipapp, https://docs.python.org/3/library/zipapp.html
python 3.7 is not available on openSUSE Leap 15.4.

```
# Use Meson's ability to install as a single file
'/usr/bin/python3' '/home/jonas/Projects/jonaski-mxe/tmp-meson-x86_64-pc-linux-gnu/meson-0.63.0/packaging/create_zipapp.py' --outfile '/home/jonas/Projects/jonaski-mxe/usr/x86_64-pc-linux-gnu/bin/meson' --interpreter '/usr/bin/python3' '/home/jonas/Projects/jonaski-mxe/tmp-meson-x86_64-pc-linux-gnu/meson-0.63.0'
Traceback (most recent call last):
  File "/home/jonas/Projects/jonaski-mxe/tmp-meson-x86_64-pc-linux-gnu/meson-0.63.0/packaging/create_zipapp.py", line 23, in <module>
    zipapp.create_archive(d, interpreter=options.interpreter, target=options.outfile, compressed=options.compress)
TypeError: create_archive() got an unexpected keyword argument 'compressed'
make[1]: *** [Makefile:900: build-only-meson_x86_64-pc-linux-gnu] Error 1
make[1]: Leaving directory '/home/jonas/Projects/jonaski-mxe'
```

I had to downgrade to meson 0.61.4 to build on Leap 15.4. Not an issue on my main machine which has tumbleweed.

**Comment by eli-schwartz** [comment]
Please note that this has nothing to do with the zipapp usage. The zipapp usage was introduced in Meson 0.62.0-180-g3e26c0f1c

However, Meson 0.61.0-12-gad525dcce dropped support for python 3.6 after it was end of lifed -- Meson 0.62.0 makes use of many python 3.7 specific features.

The 0.61.x release branch (currently at 5 not 4) has been maintained as an LTS release for python 3.6 support for this reason. And note that there are a variety of bugfixes there that you might want to use, which were fixed in 0.61.***5***

**Comment by jonaski** [comment]
According to https://docs.python.org/3/library/zipapp.html
`New in version 3.7: Added the filter and compressed arguments.`

**Comment by jonaski** [comment]
Anyway, let's not bother with this. Those who need to compile on a system without python 3.7 can just downgrade meson manually.
