### ISSUE TITLE
CMake won't build

### ISSUE THREAD

**Issue by rkfg** [mxe/mxe#1784]
Debian testing amd64, host cmake fails to build after 5780100e32ff9c0d04165ee82744b19a6e6676db
OpenSSL dev package is installed, also tried with gnutls but to no avail. Before that commit it compiles and works just fine. Log:

```
[ 67%] Linking C executable LIBCURL
lib/libcmcurl.a(openssl.c.o): In function `cert_stuff':
openssl.c:(.text+0x921): undefined reference to `sk_pop'
openssl.c:(.text+0x9ac): undefined reference to `sk_num'
openssl.c:(.text+0x9e4): undefined reference to `sk_pop_free'
lib/libcmcurl.a(openssl.c.o): In function `Curl_ossl_init':
openssl.c:(.text+0xeae): undefined reference to `SSL_load_error_strings'
openssl.c:(.text+0xeb3): undefined reference to `SSL_library_init'
openssl.c:(.text+0xec3): undefined reference to `OPENSSL_add_all_algorithms_noconf'
lib/libcmcurl.a(openssl.c.o): In function `Curl_ossl_cleanup':
openssl.c:(.text+0xed3): undefined reference to `EVP_cleanup'
openssl.c:(.text+0xed8): undefined reference to `ERR_free_strings'
openssl.c:(.text+0xee7): undefined reference to `CONF_modules_free'
openssl.c:(.text+0xeec): undefined reference to `SSL_COMP_free_compression_methods'
lib/libcmcurl.a(openssl.c.o): In function `verifyhost':
openssl.c:(.text+0x165a): undefined reference to `sk_num'
openssl.c:(.text+0x167a): undefined reference to `sk_value'
lib/libcmcurl.a(openssl.c.o): In function `ossl_connect_step1':
openssl.c:(.text+0x2442): undefined reference to `SSLv23_client_method'
openssl.c:(.text+0x2471): undefined reference to `SSLv3_client_method'
lib/libcmcurl.a(openssl.c.o): In function `X509V3_ext':
openssl.c:(.text+0x3213): undefined reference to `sk_num'
openssl.c:(.text+0x3241): undefined reference to `sk_value'
openssl.c:(.text+0x3414): undefined reference to `sk_num'
lib/libcmcurl.a(openssl.c.o): In function `get_cert_chain':
openssl.c:(.text+0x347f): undefined reference to `sk_num'
openssl.c:(.text+0x34d2): undefined reference to `sk_value'
lib/libcmcurl.a(openssl.c.o): In function `Curl_ossl_version':
openssl.c:(.text+0x513f): undefined reference to `SSLeay'
collect2: error: ld returned 1 exit status
Utilities/cmcurl/CMakeFiles/LIBCURL.dir/build.make:98: recipe for target 'Utilities/cmcurl/LIBCURL' failed
```

**Comment by tonytheodore** [comment]
What does `lsb_release -sc` return? It may be simpler to build openssl natively.

**Comment by tonytheodore** [comment]
Can you see if #1792 fixes it?

**Comment by rkfg** [comment]
Didn't help, unfortunately. `lsb_release -sc` returns `stretch`. The log is the same. Do I need some special flags to make it work? My make command is `make qtbase qtmultimedia MXE_TARGETS='i686-w64-mingw32.static.posix x86_64-w64-mingw32.static.posix' JOBS=8 -j8`

**Comment by tonytheodore** [comment]
Okay, [`stretch` was only just changed from testing to release](https://www.debian.org/releases/). I've [updated the PR](https://github.com/mxe/mxe/pull/1792/commits/2eacb9044b599bb6b5435d69f09290eaee9ff43b), can you check again?

**Comment by rkfg** [comment]
Should I do `make clean` or other cleanups prior to rebuilding? I see that after applying the patch mxe compiles openssl and zlib but cmake still fails with the same log.

**Comment by rkfg** [comment]
`make clean` didn't change anything, just tested.

**Comment by tonytheodore** [comment]
Shouldn't need any other cleanups or flags, building lib and openssl is expected and means this approach won't work - can you post the full log? There are some [patches in the Debian repo](https://anonscm.debian.org/cgit/pkg-cmake/cmake.git/tree/debian/patches?h=jessie) that may be relevant.

**Comment by rkfg** [comment]
[Here it is](https://gist.github.com/rkfg/7808ee9b19aee8026a0b35c245930dc8).

**Comment by tonytheodore** [comment]
Do you have some other experimental/cross toolchain installed in `/usr/lib/x86_64-linux-gnu`? I'd expect standard libs to be in `/usr/lib`??

**Comment by rkfg** [comment]
Almost everything in Debian goes to `/usr/lib/<arch>` due to multiarch. I have musl toolchain installed but it's in `/usr/lib/x86_64-linux-musl`. I couldn't find any other toolchains in there. Usually all I build I install into /opt/build so it won't interfere.

**Comment by tonytheodore** [comment]
I'm out of ideas for the moment, did you always use `Check for working C compiler: /usr/lib/ccache/gcc -- works`?

**Comment by rkfg** [comment]
Well, it worked for me in any other project I compiled including MXE prior to that commit. I removed ccache from PATH, [here's the new log](https://gist.github.com/rkfg/a127fe04d9cd8b0e84ef701b69bfaedb), still the same error.

**Comment by tonytheodore** [comment]
Unfortunately, I can't replicate with `libcurl4-openssl-dev libgnutls28-dev` installed or not. The [log shows](https://gist.github.com/tonytheodore/fc76e431d27346978aea6c22a6cf7ce1) it's finding the libs in the same locations, but gcc is newer and the checks for `-- Checking support for ARCHIVE_CRYPTO_SHA256_OPENSSL -- found` etc. seem to work.

**Comment by rkfg** [comment]
Ok, the solution is to remove `libssl-dev` package. It contains the symlink `/usr/lib/x86_64-linux-gnu/libcrypto.so -> libcrypto.so.1.1`. I also have a symlink `/usr/lib/x86_64-linux-gnu/libcrypto.so.1 -> libcrypto.so.1.0.2` (dpkg -S doesn't show the owner of this link so I have no idea where it came from). Some packages still require older OpenSSL while others need the newer so I can't get rid of one of them. The problem is that those functions were renamed in OpenSSL 1.1.* compared to 1.0.*, I used `readelf` to find them:
1.0.2:
```
000000451518  023200000007 R_X86_64_JUMP_SLO 000000000012ee60 sk_pop@@OPENSSL_1.0.2d + 0
```
1.1:
```
000000484240  014b00000007 R_X86_64_JUMP_SLO 00000000001bd9b0 OPENSSL_sk_pop@@OPENSSL_1_1_0 + 0
```
They've added the `OPENSSL_` prefix and thus it prevent linking. So after libssl-dev removal I was able to build cmake and other stuff. The real issue is why CMake depends on that older libssl version but that's probably beyond the MXE scope. Thanks for your help, @tonytheodore !
