### PR TITLE
remove xine-lib

### LINKED ISSUE #1232: xine-lib is broken (implicit declaration of function 'avcodec_alloc_frame')
Commit: 62467d9d4dbb69aa632ae684b4a5a3f4c3b4a1ff
OS: Debian Wheezy
Log: https://gist.github.com/d976d087336c265d6e6f

Probably this problem was introduced by 57a6850a0f427fa25ec12fec2231ae640dff9f99
See also https://github.com/mxe/mxe/issues/1230

### PR DESCRIPTION
**Pull request by starius**
fix #1232 
openscenegraph builds successfully for all 4 targets.

### CODE REVIEW

**Comment by TimothyGu** [comment]
LGTM.
