### PR TITLE
qttools: disable qdoc

### LINKED ISSUE #2324: qttools: undefined reference to `QQmlJS::AST::Visitor::Visitor(unsigned short)'
qttools won't compile since the update to 5.12.3
https://gist.github.com/jonaski/f45929a124e2029a968e9358ba805267

### PR DESCRIPTION
**Pull request by tonytheodore**
requires libclang-devel

fixes #2324

### CODE REVIEW

**Comment by jonaski** [comment]
That worked. Thanks!
