### ISSUE TITLE
libboost_thread_win32-mt won't link because of multiple definitions

### ISSUE THREAD

**Issue by Stefan-Olt** [mxe/mxe#1962]
I want to cross-compile GNU Radio, but at some point I get linking errors like:
../lib/libboost_thread_win32-mt.a(thread.o):thread.cpp:(.text+0x260): multiple definition of `boost::thread::start_thread_noexcept()'
For several functions, all in libboost_thread_win32-mt.a
This seems to be a common problem, it was reported with cross-compiling already years ago, but I could not find any solution. Any idea? GNU Radio itself compiles on Ubuntu 16.04 without any problem.

**Comment by tonytheodore** [comment]
At some point in the past, `-DBOOST_THREAD_USE_LIB` was needed but that doesn't seem the case any more.

If using cmake, `Boost_THREADAPI=win32` also may need to be set - the MXE cmake wrapper should do this for you. 

Have you got a minimal example program?

**Comment by Stefan-Olt** [comment]
I already tried `-DBOOST_THREAD_USE_LIB`, but there is no difference, this how I've tried it:
`i686-w64-mingw32.static-cmake -ENABLE_STATIC_LIBS=True -DCMAKE_CXX_FLAGS:STRING="-DBOOST_THREAD_USE_LIB" ../`
I also tried `i686-w64-mingw32.static-cmake -ENABLE_STATIC_LIBS=True -DCMAKE_CXX_FLAGS:STRING="-DBOOST_THREAD_USE_LIB -DBOOST_THREAD_WIN32 -DBOOST_THREAD_PLATFORM_WIN32" ../`, also doesn't work. But when set `-DBOOST_THREAD_POSIX` it will fail a lot earlier, so the command is recognized.

I'm sorry, I cannot provide a minimal example, but you can try yourself, this is what I have done:
`git clone https://github.com/gnuradio/gnuradio.git`
`cd gnuradio`
`mkdir buildwin`
`cd buildwin`
`i686-w64-mingw32.static-cmake -ENABLE_STATIC_LIBS=True -DCMAKE_CXX_FLAGS:STRING="-DBOOST_THREAD_USE_LIB" ../`
`make`

**Comment by tonytheodore** [comment]
Turns out to have nothing to do with boost, but with `__declspec` issues. The below will get you up to
```
make gnuradio-runtime gnuradio-runtime_static
```
you'll have to add similar changes in the other subdirectories:

```diff
diff --git a/gnuradio-runtime/include/gnuradio/attributes.h b/gnuradio-runtime/include/gnuradio/attributes.h
index 250683f24..180832b3d 100644
--- a/gnuradio-runtime/include/gnuradio/attributes.h
+++ b/gnuradio-runtime/include/gnuradio/attributes.h
@@ -30,9 +30,16 @@
 #  define __GR_ATTR_UNUSED     __attribute__((unused))
 #  define __GR_ATTR_INLINE     __attribute__((always_inline))
 #  define __GR_ATTR_DEPRECATED __attribute__((deprecated))
-#  if __GNUC__ >= 4
+#  if __GNUC__ >= 4 && !defined(_WIN32)
 #    define __GR_ATTR_EXPORT   __attribute__((visibility("default")))
 #    define __GR_ATTR_IMPORT   __attribute__((visibility("default")))
+#  elif defined(_WIN32)
+#    define __GR_ATTR_EXPORT   __declspec(dllexport)
+#    if GR_STATIC
+#      define __GR_ATTR_IMPORT
+#    else
+#      define __GR_ATTR_IMPORT __declspec(dllimport)
+#    endif
 #  else
 #    define __GR_ATTR_EXPORT
 #    define __GR_ATTR_IMPORT
diff --git a/gnuradio-runtime/lib/CMakeLists.txt b/gnuradio-runtime/lib/CMakeLists.txt
index 1180ebec7..e6a58b704 100644
--- a/gnuradio-runtime/lib/CMakeLists.txt
+++ b/gnuradio-runtime/lib/CMakeLists.txt
@@ -229,6 +229,7 @@ if(ENABLE_STATIC_LIBS)
   endif(ENABLE_GR_CTRLPORT)
 
   add_library(gnuradio-runtime_static STATIC ${gnuradio_runtime_sources})
+  set_property(TARGET gnuradio-runtime_static APPEND PROPERTY COMPILE_DEFINITIONS "GR_STATIC")
 
   if(NOT WIN32)
     set_target_properties(gnuradio-runtime_static
diff --git a/gnuradio-runtime/lib/pmt/CMakeLists.txt b/gnuradio-runtime/lib/pmt/CMakeLists.txt
index 32c0e57a6..d8a88c1a7 100644
--- a/gnuradio-runtime/lib/pmt/CMakeLists.txt
+++ b/gnuradio-runtime/lib/pmt/CMakeLists.txt
@@ -116,6 +116,7 @@ add_dependencies(gnuradio-pmt
 
 if(ENABLE_STATIC_LIBS)
   add_library(gnuradio-pmt_static STATIC ${pmt_sources})
+  set_property(TARGET gnuradio-pmt_static APPEND PROPERTY COMPILE_DEFINITIONS "GR_STATIC")
 
   add_dependencies(gnuradio-pmt_static pmt_generated)
 
```

**Comment by Stefan-Olt** [comment]
Thanks, that seems to do the trick!
