### PR TITLE
openscenegraph: disable ffmpeg

### LINKED ISSUE #1230: openscenegraph is broken ('AVCod ecContext' has no member named 'get_buffer')
Commit: 62467d9d4dbb69aa632ae684b4a5a3f4c3b4a1ff
OS: Debian Wheezy
Log: https://gist.github.com/822e7f77a7158fe79b84

Probably this problem was introduced by 57a6850a0f427fa25ec12fec2231ae640dff9f99

### PR DESCRIPTION
**Pull request by starius**
fix #1230

### CODE REVIEW

File: src/openscenegraph-1-fixes.patch [hunk 1]
```diff
@@ -155,3 +155,30 @@ index 1111111..2222222 100644
...
+From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
+From: Boris Nagaev <bnagaev@gmail.com>
+Date: Mon, 22 Feb 2016 03:35:28 +0300
+Subject: [PATCH] disable ffmpeg
+
+OpenSceneGraph is using removed features of ffmpeg, which have
+been deprecated for 3+ years.
+
+See https://github.com/mxe/mxe/issues/1230#issuecomment-186936198
+Source of patch: http://forum.openscenegraph.org/viewtopic.php?t=13884
```
Comment (TimothyGu) [inline src/openscenegraph-1-fixes.patch]: This URL is wrong.

Comment (starius) [inline src/openscenegraph-1-fixes.patch]: FIxed.
