### ISSUE TITLE
sdl_sound: undefined reference to `_imp__FLAC__stream_decoder_new'

### ISSUE THREAD

**Issue by jonaski** [mxe/mxe#2903]
sdl_sound test fails to build with undefined reference to `_imp__FLAC__stream_decoder_new'.
Full log: https://gist.github.com/jonaski/7696f5d6e60d90f4361b37627d8ef662

**Comment by jonaski** [comment]
@mabrand It builds with flac 1.3.3, seem to have happened after you upgraded flac to 1.4.0.

**Comment by jonaski** [comment]
Similar issue with fluidsynth and sox (if I disable sndfile).
