### ISSUE TITLE
qttools: undefined reference to `QQmlJS::AST::Visitor::Visitor(unsigned short)'

### ISSUE THREAD

**Issue by jonaski** [mxe/mxe#2324]
qttools won't compile since the update to 5.12.3
https://gist.github.com/jonaski/f45929a124e2029a968e9358ba805267

**Comment by tonytheodore** [comment]
It's changed the way `clang` detection works and that's too heavyweight a requirement to build docs. Can you try:
```diff
diff --git a/src/qttools.mk b/src/qttools.mk
index 24171a46..6f4e61ad 100644
--- a/src/qttools.mk
+++ b/src/qttools.mk
@@ -19,7 +19,7 @@ define $(PKG)_UPDATE
 endef

 define $(PKG)_BUILD
-    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG+=config_clang_done CONFIG-=config_clang
+    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG-=qdoc
     $(MAKE) -C '$(1)' -j '$(JOBS)'
     $(MAKE) -C '$(1)' -j 1 install

@@ -32,7 +32,7 @@ define $(PKG)_BUILD
 endef

 define $(PKG)_BUILD_$(BUILD)
-    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG+=config_clang_done CONFIG-=config_clang
+    cd '$(1)' && '$(PREFIX)/$(TARGET)/qt5/bin/qmake' CONFIG-=qdoc
     $(MAKE) -C '$(1)' -j '$(JOBS)'
     $(MAKE) -C '$(1)' -j 1 install
 endef
```

**Comment by jonaski** [comment]
Same problem

**Comment by tonytheodore** [comment]
How about #2325?
