### ISSUE TITLE
xine-lib is broken (implicit declaration of function 'avcodec_alloc_frame')

### ISSUE THREAD

**Issue by starius** [mxe/mxe#1232]
Commit: 62467d9d4dbb69aa632ae684b4a5a3f4c3b4a1ff
OS: Debian Wheezy
Log: https://gist.github.com/d976d087336c265d6e6f

Probably this problem was introduced by 57a6850a0f427fa25ec12fec2231ae640dff9f99
See also https://github.com/mxe/mxe/issues/1230

**Comment by starius** [comment]
I tried to fix this issue by replacing `avcodec_alloc_frame` with `av_frame_alloc` and `avcodec_free_frame` with `av_frame_free`. Patch: https://gist.github.com/ee227c120267fcdd9ef0

It compiles, but `xine-list-1.2.exe` crashes. It also crashes without my patch before 57a6850a0f427fa25ec12fec2231ae640dff9f99 (update of ffmpeg).

**Comment by TimothyGu** [comment]
Newer FFmpeg uses refcounting and `av_frame_free` and `av_frame_alloc` are usually not needed. I'd remove xine-lib as well.
